### PR TITLE
Add systemd unit to control prime_encoder service

### PR DESCRIPTION
**Pull request by yoavp77**

### CODE REVIEW

**Comment by jwittkoski** [comment]
Joe,
Thanks for contributing! I'd like to add User and Group values here also so this file matches what `prime_encoder.init` does. If you'd like to update the PR that would be great, or I can do it with a separate commit.

**Comment by yoavp77** [comment]
Sure, I can do that. Would you also be open to a PR updating `prime_encoder` to read values like `encoder.id` and `ffmpeg_cmd` from a config file? My perl is stale but I can take a crack at that.

**Comment by jwittkoski** [comment]
You didn't need to close this PR, you can append to it.

**Comment by jwittkoski** [comment]
About the config file, I have been working on some changes that include that, so don't worry about that part! Thank you for the offer!

**Pull request closed without merging**
